// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMr3ycJWBQZL1kfPIy1I74JWZSuzeJhjU',
    appId: '1:43272927608:web:934f0913fc1d9e4839708d',
    messagingSenderId: '43272927608',
    projectId: 'flutterfire-ui-codelab-ea225',
    authDomain: 'flutterfire-ui-codelab-ea225.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-ea225.appspot.com',
    measurementId: 'G-5XE8BX747D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfax6TjC0wXGRhYw7mVODPjNHtQaoiySw',
    appId: '1:43272927608:android:b89d3772cb13b19939708d',
    messagingSenderId: '43272927608',
    projectId: 'flutterfire-ui-codelab-ea225',
    storageBucket: 'flutterfire-ui-codelab-ea225.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvNcg5oOAQer7MruPyCSUan7S79bz_g5g',
    appId: '1:43272927608:ios:e634578ef14a671039708d',
    messagingSenderId: '43272927608',
    projectId: 'flutterfire-ui-codelab-ea225',
    storageBucket: 'flutterfire-ui-codelab-ea225.appspot.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvNcg5oOAQer7MruPyCSUan7S79bz_g5g',
    appId: '1:43272927608:ios:c8ab5a7fea08d90d39708d',
    messagingSenderId: '43272927608',
    projectId: 'flutterfire-ui-codelab-ea225',
    storageBucket: 'flutterfire-ui-codelab-ea225.appspot.com',
    iosBundleId: 'com.example.complete.RunnerTests',
  );
}
